USE FLUXO_DE_CAIXA;
DELETE FROM CAIXAS;

INSERT INTO CAIXAS (STATUS, VALOR, TIPO) VALUES (2, 80.00, 'Fone de ouvido');
INSERT INTO CAIXAS (STATUS, VALOR, TIPO) VALUES (2, 10.90, 'Salgado');
INSERT INTO CAIXAS (STATUS, VALOR, TIPO) VALUES (2, 1800.00, 'Aluguel');
INSERT INTO CAIXAS (STATUS, VALOR, TIPO) VALUES (2, 1000.50, 'Manutenção de Notebook');
INSERT INTO CAIXAS (STATUS, VALOR, TIPO) VALUES (2, 120.00, 'Teclado');
INSERT INTO CAIXAS (STATUS, VALOR, TIPO) VALUES (2, 100.50, 'Mercado');
INSERT INTO CAIXAS (STATUS, VALOR, TIPO) VALUES (1, 5000.00, 'Salário');